package tuvarna.ticket_center_common.requests;

public enum RequestCodes {

    USERS_LOGIN
    , USERS_REGISTER
    , USERS_VERIFY
    , USERS_CHANGE_PASSWORD
    , USERS_EDIT
    , USERS_GET

    , EVENTS_POST
    , EVENTS_GET
    , EVENTS_EDIT
    , EVENTS_GET_ASSIGNED
    , EVENTS_TICKETS_GET
    , EVENTS_TICKETS_CHECK_IN
    , EVENTS_TICKETS_CHECK_OUT
    , EVENTS_TICKETS_PURCHASE

    , DISTRIBUTORS_GET
    , DISTRIBUTORS_POST
    , DISTRIBUTORS_EDIT
    , DISTRIBUTORS_GET_ASSIGNED
    , DISTRIBUTORS_GET_FREE
    , DISTRIBUTORS_ASSIGN

    , RATINGS_POST
    , RATINGS_GET
}
